# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eba427d1861d8cd9d85333b49ce7903ba20e63f8dae819e1185b4f6caa50093afb53b90aeb430c9c83f861aa2e6ed5fd424db443b09ccf6a8ce7e74f8ac53fac

test:
  secret_key_base: d113c1b6416247533b6f6129443309adb5b9422d208c0e494dd85ba55d5845faf3eafabf917159c767f7993cee8bafd5a3a88ab1c587ceec1cc829d8977472c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
